cooldown: 30
prices:
  DIRT: 1.0
items:
  WOODEN_WAND:
    Name: '&eWooden Sell-Wand'
    Type: 'WOODEN_HOE'
    lore:
      - '&7Right-click a chest with'
      - '&7this wand to sell it''s'
      - '&7contents.'
    Enchanted: false
    Uses: 300
  IRON_WAND:
    Name: '&7Iron Sell-Wand'
    Type: 'IRON_HOE'
    Lore:
      - '&7Right-click a chest with'
      - '&7this wand to sell it''s'
      - '&7contents.'
    Enchanted: false
    Uses: 800
  DIAMOND_WAND:
    Name: '&bDiamond Sell-Wand'
    Type: 'DIAMOND_HOE'
    Lore:
      - '&7Right-click a chest with'
      - '&7this wand to sell it''s'
      - '&7contents.'
    Enchanted: true
    Uses: 1500
price-multiplier: 1.0
sale-breakdown: true
messages:
  cooldown: '&cYou must wait %seconds% seconds to sell again.'
  sale: '&2&lSold all items for &a&l$%amount%&2&l:'
  sale-breakdown: '&8 * &a%item% (x%amount%) for $%price%.'
  item-give: '&aGiven %player% a sell wand.'
  item-receive: '&aReceived a sell wand.'
  item-use: '&aYour sell wand now has &2%uses% &auses left.'
  item-use-lore: '&aUses: &2%uses%'
  item-use-empty: '&cNothing inside the chest is sellable.'
  item-break: '&cYour sell wand has no more uses left.'
  no-permission: '&cYou do not have permission to use sell wands.'