name: SellWands
version: maven-version-number
description: SellWands
author: Songoda
main: com.songoda.sellwands.SellWands
depend: [Vault]
softdepend: [ModdedCore, Barrels]
api-version: 1.13

commands:
  sellwands:
    description: Give other players sell wands.
    usage: /sellwands
  sellwand:
    description: Give yourself a sell wand.
    usage: /sellwand