name: EpicSellWands
version: maven-version-number
description: EpicSellWands
author: Songoda
main: com.songoda.epicsellwands.EpicSellWands
depend: [Vault]
softdepend: [ModdedCore]
api-version: 1.13

commands:
  esw:
    description: Give other players sell wands.
    usage: /sellwands
    aliases: [EpicSellWands]